#!/bin/bash

# Compile the key generator
gcc -o keygen keygen.c

# Compile encoding programs
gcc -o otp_enc otp_enc.c
gcc -o otp_enc_d otp_enc_d.c

# Compile decoding programs
gcc -o otp_dec otp_dec.c
gcc -o otp_dec_d otp_dec_d.c
